services:
  backend:
    build: ./backend/project  
    ports:
      - "8000:8000"
    volumes:
      - ./backend/project:/backend
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db_host

  db_host:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: minh_hiep
      POSTGRES_DB: mydb
    ports:
      - '5432'
      
  frontend:
    build: ./frontend/react-project
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/react-project:/frontend
volumes:
  my_app:
