# Generated by Django 4.2.9 on 2024-03-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_price', '0002_alter_stockmodel_symbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('symbol', models.CharField(max_length=10)),
                ('scrapped_date', models.DateField()),
                ('headline', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddConstraint(
            model_name='newsmodel',
            constraint=models.UniqueConstraint(fields=('url', 'symbol'), name='unique_field_pair'),
        ),
    ]
